# -*- coding: utf-8 -*-
"""Crypto Price Alert.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FxvrK6-Z0yxKOyfEbw5y1eRz95VBp0V_
"""

from bs4 import BeautifulSoup
import requests
import time
import smtplib 
import ssl
from email.mime.text import MIMEText as MT
from email.mime.multipart import MIMEMultipart as MM

def get_price():
  url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=USD&order=market_cap_d'
  
  contents =requests.get(url)
  d = contents.json()
  return d[0]["current_price"]

receiver = '<Receiver Email>'
sender = '<Sender Mail'
pwd = '<Your password>'

#function to send emails

def send_email(sender,receiver,pwd,price):
  msg = MM()
  msg['Subject'] = "BIT COIN PRICE ALERT!!!" 
  msg['From'] = sender
  msg['To'] = receiver

  html = """
        <html>
          <body>
            <h1>  New Price   </h2>
            <h2>""" + price +""" <h2>
          </body>
        </html>  

        """
  mtobj = MT(html,"html")
  msg.attach(mtobj)      

  #creating SSL Layer object
  SSL_context = ssl.create_default_context()

  #creating SMTP connection
  server = smtplib.SMTP_SSL(host='smtp.gmail.com',port = 465,context=SSL_context)

  server.login(sender,pwd)

  server.sendmail(sender,receiver,msg.as_string())

def alert():
  last_price = - 1;
  curr_price = get_price()

  while(last_price != curr_price):
    message = 'Current Bitcoin price is ' + str(curr_price)
    print(message)
    send_email(sender,receiver,pwd,message)
    last_price = curr_price
    curr_price = get_price()

alert()

